[auth]
redirect_uri = "https://vintedautomationsalescontrol.streamlit.app/oauth2callback"
cookie_secret = "Xv7mQ9rK2pL8sN4uWc3Yh6Tf1Dz5Ba0JeR7vMn2Qk8Lp4Xs9Ct6Uw3Hb5Ny1"
client_id = "785481707558-a9693l8r8sec7uffdo1cgi2q1n4srfhh.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configurati. on"